### ISSUE TITLE
Lead does not include source_id in OPTS_KEYS_TO_PERSIST

### ISSUE THREAD

**Issue by nhoffmann** [basecrm/basecrm-ruby#24] opened 2015-09-03 13:08 UTC
The api documentation for [create_lead](https://developers.getbase.com/docs/rest/reference/leads#create_lead) lists `source_id` as an attribute that may be set thorugh a `POST /leads`. Unfortunately `source_id` is not included in the `OPTS_KEYS_TO_PERSIST` for the `LeadService` and thus gets thrown out during sanitization.

I get that the Services get auto-generated from a JSON schema and the fix probably has to made there. I'd be happy to provide a PR if somebody can point me to where this JSON schema is located.

**Comment by iaintshine** [comment] 2015-09-24 20:37
Duplicate of #22.

**Closed by iaintshine** 2015-09-24 20:37 UTC
