### ISSUE TITLE
JSON version in gemspec is old

### ISSUE THREAD

**Issue by mjankowski** [basecrm/basecrm-ruby#49] opened 2017-09-28 14:55 UTC
It looks like this library is not regularly maintained ... should it work with newer ruby versions?

For example, in Ruby 2.4.2, a simple require seems to not work...

```
irb(main):001:0> require "basecrm"
=> true
irb(main):002:0> BaseCRM::Client
NameError: uninitialized constant BaseCRM
```

...whereas in ruby 2.0.0, it does...

```
irb(main):001:0> require "basecrm"
=> true
irb(main):002:0> BaseCRM::Client
=> BaseCRM::Client
```

**Comment by efedasz** [comment] 2017-09-29 09:03
Hey @mjankowski. Each ruby version has a separate gems pool. So probably you don't have `basecrm` gem for ruby `2.0.0`. `bundle install` should resolve it.

**Comment by mjankowski** [comment] 2017-09-29 13:23
I'm using rbenv, and have the gem installed in both versions. Here's some larger output showing that the gem is installed for both ruby versions, and repeating the prior reported issue:

```
magicvault:~ mjankowski$ ruby -v
ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-darwin16]
magicvault:~ mjankowski$ gem list -d basecrm

*** LOCAL GEMS ***

basecrm (0.1.2)
    Author: Marcin Bunsch
    Homepage: https://github.com/basecrm/basecrm
    Installed at: /Users/mjankowski/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0

    Base CRM API Client
magicvault:~ mjankowski$ irb
irb(main):001:0> require "basecrm"
=> true
irb(main):002:0> BaseCRM::Client
NameError: uninitialized constant BaseCRM
Did you mean?  BaseCrm
	from (irb):2
	from /Users/mjankowski/.rbenv/versions/2.4.2/bin/irb:11:in `<main>'
irb(main):003:0> exit
magicvault:~ mjankowski$ rbenv local 2.0.0-p648
magicvault:~ mjankowski$ ruby -v
ruby 2.0.0p648 (2015-12-16 revision 53162) [x86_64-darwin16.5.0]
magicvault:~ mjankowski$ gem list -d basecrm

*** LOCAL GEMS ***

basecrm (1.2.2)
    Author: BaseCRM developers
    Homepage: https://github.com/basecrm/basecrm-ruby
    License: MIT
    Installed at: /Users/mjankowski/.rbenv/versions/2.0.0-p648/lib/ruby/gems/2.0.0

    BaseCRM Official API V2 library client for ruby
magicvault:~ mjankowski$ irb
irb(main):001:0> require "basecrm"
=> true
irb(main):002:0> BaseCRM::Client
=> BaseCRM::Client
irb(main):003:0> exit
magicvault:~ mjankowski$ 
```

I went back a few ruby versions and repeated this exercise ... I get the same error in ruby 2.1, 2.2, and 2.3 ... I wonder if something changed with constant handling between 2.0 and 2.1?

Can you confirm that you don't see this behavior in versions 2.1+ ?

**Comment by efedasz** [comment] 2017-09-29 13:51
The issue isn't in ruby version. I can see that you have installed very old basecrm gem (v0.1.2) for ruby 2.4.2 which, indeed, doesn't have `BaseCRM` module.

**Comment by mjankowski** [comment] 2017-09-29 13:51
Ah ha! That is ... bizarre, but definitely explains this.

I'll dig through my Gemfile to see if there are dependencies forcing the old version.

**Comment by mjankowski** [comment] 2017-09-29 13:57
I have json locked to a newer version in the project I'm trying to add basecrm to, but the gem has this requirement: https://github.com/basecrm/basecrm-ruby/blob/master/basecrm.gemspec#L24

Would it be possible to relax the json gem version requirement in the `basecrm` gem?

**Comment by efedasz** [comment] 2017-09-29 14:03
I'll schedule maintenance release, please expect new version in following week.

**Comment by mjankowski** [comment] 2017-09-29 14:06
Thanks! (renaming this issue to capture the actual problem here)

**Comment by efedasz** [comment] 2017-10-02 14:17
@mjankowski enjoy version 1.2.3
Please notice, from next version we will set json dependency on "~> 2.0". Closing.

**Closed by efedasz** 2017-10-02 14:17 UTC

**Comment by mjankowski** [comment] 2017-10-02 14:30
Thanks!
