### ISSUE TITLE
Library not posting source_id when leads are created

### ISSUE THREAD

**Issue by jpatel531** [basecrm/basecrm-ruby#22] opened 2015-08-08 16:47 UTC
Hi there - I don't believe the source_id is being posted to the Base v2 API. I can't find it in the `lead` model either

**Comment by itsderek23** [comment] 2015-08-29 16:14
+1. Seeing the same behavior on update as well.

**Comment by nhoffmann** [comment] 2015-09-03 14:22
#24

**Comment by nhoffmann** [comment] 2015-09-03 14:25
I just ran into the same thing. The `source_id`attribute gets cleaned up during sanitization because it is not included in the `OPTS_KEYS_TO_PERSIST` set. I guess with  #24 I created a duplicate of this ticket then.

**Comment by efedasz** [comment] 2017-10-02 14:19
Should be ok in version `1.2.3`, closing.

**Closed by efedasz** 2017-10-02 14:19 UTC
Labels: enhancement
